// PARK ACTIONS

export const PARK_ACTION_START = 'PARK_ACTION_START'
export const PARK_ACTION_FAIL = 'PARK_ACTION_FAIL'

export const FETCH_PARK_SUCCESS = 'FETCH_PARK_SUCCESS';
export const FETCH_PARKS_SUCCESS = 'FETCH_PARKS_SUCCESS';

export const UPDATE_PARK_FILTER = 'UPDATE_PARK_FILTER';
export const RESET_PARK_FILTER = 'RESET_PARK_FILTER';

// DOG ACTIONS

export const DOG_ACTION_START = 'DOG_ACTION_START'
export const DOG_ACTION_FAIL = 'DOG_ACTION_FAIL'

export const FETCH_DOGS_SUCCESS = 'FETCH_DOGS_SUCCESS';
export const FETCH_DOG_SUCCESS = 'FETCH_DOG_SUCCESS';
export const FETCH_DOG_ATTRIBUTE_SUCCESS = 'FETCH_DOG_ATTRIBUTE_SUCCESS';

export const CREATE_EDIT_DOG_SUCCESS = 'CREATE_EDIT_DOG_SUCCESS';
export const DELETE_DOG_SUCCESS = 'DELETE_DOG_SUCCESS';

export const UPDATE_DOG_FILTER = 'UPDATE_DOG_FILTER';
export const RESET_DOG_FILTER = 'RESET_DOG_FILTER';

// USER ACTIONS

export const USER_ACTION_START = 'USER_ACTION_START';
export const USER_ACTION_FAIL = 'USER_ACTION_FAIL';

export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';

export const UPDATE_USER_FILTER = 'UPDATE_USER_FILTER';
export const RESET_USER_FILTER = 'RESET_USER_FILTER';

export const REMOVE_SELECTED_USER = 'REMOVE_SELECTED_USER';
export const REMOVE_CURRENT_USER = 'REMOVE_CURRENT_USER';

// AUTH ACTIONS

export const AUTH_ACTION_START = 'AUTH_ACTION_START';
export const AUTH_ACTION_FAIL = 'AUTH_ACTION_FAIL';

export const FETCH_CURRENT_USER_SUCCESS = 'FETCH_CURRENT_USER_SUCCESS';

export const UPDATE_CURRENT_USER_SUCCESS = 'UPDATE_CURRENT_USER_SUCCESS';
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';

export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const USER_SIGN_UP_SUCCESS = 'USER_SIGN_UP_SUCCESS';

export const UPDATE_AUTHENTICATING_STATE = 'UPDATE_AUTHENTICATING_STATE';
export const UPDATE_SIGN_UP_STATE = 'UPDATE_SIGN_UP_STATE';
export const HANDLE_USER_LOGIN = 'HANDLE_USER_LOGIN'


// NEIGHBORHOOD ACTIONS

export const NEIGHBORHOOD_ACTION_START = 'NEIGHBORHOOD_ACTION_START';
export const NEIGHBORHOOD_ACTION_FAIL = 'NEIGHBORHOOD_ACTION_FAIL';
export const FETCH_NEIGHBORHOODS_SUCCESS = 'FETCH_NEIGHBORHOODS_SUCCESS';




